services:
  - type: web_service
    name: kahianga-tracker
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: "3000"
  
  - type: pserv
    name: kahianga-db
    plan: free
    ipAllowList: []
